package com.tranche.common.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    INVALID_CREDENTIALS,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    CONFLICT,
    INVALID_ROLE,
    PROFILE_ALREADY_EXISTS,
    INVALID_STATE_TRANSITION,
    OPPORTUNITY_NOT_EDITABLE,
    OPPORTUNITY_NOT_LIVE,
    INSUFFICIENT_UNITS,
    INSUFFICIENT_FUNDS,
    BELOW_MINIMUM_LOT,
    MISSING_IDEMPOTENCY_KEY,
    INTERNAL_ERROR
}
