package com.tranche.common.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    INVALID_CREDENTIALS,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    CONFLICT,
    INVALID_ROLE,
    PROFILE_ALREADY_EXISTS,
    INVALID_STATE_TRANSITION,
    OPPORTUNITY_NOT_EDITABLE,
    INTERNAL_ERROR
}
